language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.0
env:
  - MIX_ENV=test

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env

script:
  - mix coveralls -u
  - mix credo list --ignore readability,design,refactor

cache:
  - cargo