language: elixir
elixir:
  - 1.6.1
otp_release:
  - 20.2.2

env:
  - MIX_ENV=test

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env

script:
  - mix coveralls -u
  - mix credo list --ignore readability,design,refactor

cache:
  directories:
    - $HOME/.cargo
    - deps
    - _build
